[package]
name = "MOS_6502_EMU"
version = "0.1.0"
authors = ["lvntky <klevent1903@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
